# Generated by Django 5.1.6 on 2025-02-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Co-op', 'Co-op'), ('Full-time', 'Full-time'), ('Program', 'Program'), ('Part-time', 'Part-time')], default='Internship', max_length=100)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_name', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_exp', to='api.experience')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_exp', to='api.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Application Sent', 'Application Sent'), ('Rejected', 'Rejected'), ('Response', 'Response'), ('Interview', 'Interview'), ('Offer', 'Offer')], default='Application Sent', max_length=20)),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Co-op', 'Co-op'), ('Full-time', 'Full-time'), ('Program', 'Program'), ('Part-time', 'Part-time')], default='Internship', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('submitted_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resume')),
            ],
        ),
    ]
