# Generated by Django 5.1.6 on 2025-02-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='user_id',
            new_name='user',
        ),
    ]
