# Generated by Django 5.1.6 on 2025-02-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
